// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_temperature_measurement         19
#define gattdb_temperature_type                22
#define gattdb_thermostadt_humidity            25
#define gattdb_thermostadt_humidity_hyst_high         27
#define gattdb_thermostadt_humidity_set         29
#define gattdb_thermostadt_humidity_hyst_low         31
#define gattdb_thermostadt_outputs             33
#define gattdb_thermostadt_temperature         35
#define gattdb_thermostadt_temperature_hyst_high         37
#define gattdb_thermostadt_temperature_set         39
#define gattdb_thermostadt_temperature_hyst_low         41
#define gattdb_ota_control                     44

#endif
